github_org = "caarlos0"
repositories = [
  "alelobot",
  "alelogo",
  "am-i-working",
  "clone-org",
  "dotfiles",
  "env",
  "example",
  "fork-cleaner",
  "git-gc",
  "github-buildkite-wire",
  "github-vacations",
  "gohome",
  "jvm",
  "karmahub",
  "machine",
  "macOS",
  "org-stats",
  "route53-cleaner",
  "shell-ci-build",
  "spin",
  "twatcher",
  "watchub",
  "zsh-git-sync",
  "zsh-open-pr"
]
